server:
  port: 5465
  servlet:
    context-path: /
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  application:
    name: ZLink
  datasource:
    username: root
    password: 111
    url: jdbc:mysql://192.168.25.110:3367/zlink
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapperLocations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zlink.entity
  global-config:
    banner: false
    db-config:
      id-type: auto
  configuration:
    ## 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

loggig:
  config: classpath:log4j2.xml