server:
  port: 5465
  servlet:
    context-path: /api                            # ! 测试/生产环境替换
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  application:
    name: ZLink
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.52.154:3306/zlink
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zlink.entity
  global-config:
    db-config:
      id-type: auto